[build]
  # 프로젝트의 실제 base 디렉토리 경로 지정
  base = "/"
  # 빌드 명령어
  command = "npm run build"
  # 빌드 결과물이 생성되는 디렉토리
  publish = "dist"
[[redirects]]
  from = "/*"
  to = "/index.html"
status = 200